baseurl = "https://devcows.github.io/hugo-universal-theme/"
defaultContentLanguage = "en"
disqusShortname = "devcows"
googleAnalytics = ""
languageCode = "en-us"
paginate = 10
theme = "hugo-universal-theme"
themesDir = "../.."
title = "Universal"
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "/contact/"
weight = 4
[[menu.main]]
identifier = "faq"
name = "FAQ"
url = "/faq/"
weight = 3
[[menu.main]]
identifier = "blog"
name = "Blog"
url = "/blog/"
weight = 2
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[[menu.topbar]]
name = "Email"
pre = "<i class='fas fa-2x fa-envelope'></i>"
url = "mailto:hello@universal.com"
weight = 4
[[menu.topbar]]
name = "Twitter"
pre = "<i class='fab fa-2x fa-twitter'></i>"
url = "http://twitter.com"
weight = 3
[[menu.topbar]]
name = "Facebook"
pre = "<i class='fab fa-2x fa-facebook'></i>"
url = "http://facebook.com"
weight = 2
[[menu.topbar]]
name = "GitHub"
pre = "<i class='fab fa-2x fa-github'></i>"
url = "https://github.com/devcows/hugo-universal-theme"
weight = 1
[params]
about_us = "<p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas.</p>"
address = "<p class=\"text-uppercase\"><strong>Universal Ltd.</strong>\n        <br>13/25 New Avenue\n        <br>Newtown upon River\n        <br>45Y 73J\n        <br>England\n        <br>\n        <strong>Great Britain</strong>\n      </p>\n      "
author = "DevCows"
contact_form_ajax = false
copyright = "Copyright (c) 2015 - 2016, YourCompany; all rights reserved."
date_format = "January 2, 2006"
defaultDescription = "Site template made by devcows using hugo"
defaultKeywords = ["devows", "hugo", "go"]
default_sharing_image = "img/sharing-default.png"
enableGoogleMaps = true
enableRecaptchaInContactForm = false
facebook_site = ""
formspree_action = "https://formspree.io/sample/of/endpoint"
googleMapsApiKey = "AIzaSyAv7Sza8NSp9_l_g8G2vlo0H4ydEPn_2jY"
googleRecaptchaKey = "site_key_for_google_recaptcha"
latitude = "-12.043333"
logo = "img/logo.png"
logo_small = "img/logo-small.png"
longitude = "-77.028333"
mainSections = ["blog"]
style = "default"
twitter_site = "GoHugoIO"
viewMorePostLink = "/blog/"
[params.carouselCustomers]
auto_play = false
items = 6
pagination_speed = 1000
slide_speed = 2000
[params.carouselHomepage]
auto_play = true
enable = true
pagination_speed = 1000
slide_speed = 2000
[params.carouselTestimonals]
auto_play = false
items = 4
pagination_speed = 1000
slide_speed = 2000
[params.clients]
enable = true
subtitle = ""
title = "Our Clients"
[params.features]
enable = true
[params.recent_posts]
enable = true
hide_summary = false
subtitle = "Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo."
title = "From our blog"
[params.see_more]
enable = true
icon = "far fa-file-alt"
link_text = "Check other homepages"
link_url = "#"
subtitle = "We have prepared for you more than 40 different HTML pages, including 5 variations of homepage."
title = "Do you want to see more?"
[params.testimonials]
enable = true
subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."
title = "Testimonials"
[params.topbar]
enable = true
text = "<p class=\"hidden-sm hidden-xs\">Contact us on +420 777 555 333 or hello@universal.com.</p>\n      <p class=\"hidden-md hidden-lg\"><a href=\"tel:+420 777 555 333\" data-animate-hover=\"pulse\"><i class=\"fas fa-phone\"></i></a>\n      <a href=\"mailto:hello@universal.com\" data-animate-hover=\"pulse\"><i class=\"fas fa-envelope\"></i></a>\n      </p>\n      "
[params.widgets]
categories = true
search = true
tags = true
[permalinks]
blog = "/blog/:year/:month/:day/:filename/"
[taxonomies]
author = "authors"
category = "categories"
tag = "tags"
